name: Build

on:
  push:
    branches: ["**"]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 16
        distribution: 'adopt'
 
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-maven2-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven2-

    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
 
    - name: Build
      run: |
        mvn clean package "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
        mkdir dist
        mv target/npcsystem-*.jar ./dist
      env:
        GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
        GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Plugin
        path: dist/