name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 16
        distribution: 'adopt'
 
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}

    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
 
    - name: Build
      run: |
        mvn clean package "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
        mkdir dist
        mv target/npcsystem-*.jar ./dist
      env:
        GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
        GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD  }}

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        servers: '[{ "id": "nexus", "username": "deployment", "password": "${{ secrets.NEXUS_DEPLOYMENT }}" }]'
 
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        name: Release ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GH_PACKAGE_REPO_PASSWORD  }}

    - name: Publish to GitHub Packages
      run: mvn -Daether.connector.basic.threads=1 -s ~/.m2/settings.xml --batch-mode deploy "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}